name: Lint check of CSS
on:
  push:
    paths:
      - '**.scss'
      - '**.sass'
      - '**.css'
      - '**.vue'
      - .stylelintignore
      - .stylelintrc
      - .github/workflows/eslint.yml

jobs:
  build:
    name: stylelint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: yarn install
      - name: Run stylelint check
        run: yarn run lint:css --fix
      - name: Commit and Push
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "👕 Fixed auto-fixable stylelint errors by github-actions"; \
            git push origin HEAD:${GITHUB_REF}; \
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
