name: Type checking of TypeScript
on:
  push:
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
      - '**.vue'
      - package.json
      - .github/workflows/type-check.yml

jobs:
  build:
    name: Check types
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: yarn install
      - name: Run type check
        run: yarn build --spa
