name: Run fixpack
on:
  push:
    paths:
      - package.json
jobs:
  fixpack:
    name: fixpack
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install fixpack
        run: yarn global add fixpack
      - name: Run fixpack
        run: fixpack
      - name: Commit and Push
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "🔨 Fixed package.json formats."; \
            git push origin HEAD:${GITHUB_REF}; \
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}